hydra:
  output_subdir: null
  run:
    # current dir when you read this file..
    dir: ./


defaults:
  # # reward_lm: ???
  - reward_lm: gpt4-0613


# path: null
path: ???
batch_size: 4

# if only reward the instances that are classified as harmful before
only_prev_harms:
  - beaver
  - harmbench




