hydra:
  output_subdir: null
  run:
    # current dir when you read this file..
    dir: ./

defaults:
  - reward_lm: reward_lm
  - target_lm: vicuna-chat
  - prompter_lm: prompter_lm
  - generation_configs@prompter_lm: greedy
  - _self_


reward_lm:
  debug: false
target_lm:
  debug: false
data_args:
  all_queries_path: ./data/harmful_q_target.json
  prompt_type: q_p
  split_path: data/train_val_test.json
  split: null

prompter_lm:
  model_name: /research/nfs_sun_397/liao.629/why_attack/ckpt/prompter_vicuna_ckpt_llama2-base_q_r_p
  # data .. ckpt original model ... prompt concatenation ...
  show_name: prompter_vicuna_ckpt_llama2-base_q_r_p
ppl: false
batch_size: 4
append_label_length: -1
s_p_t_dir: ./prompter_test_results
prompt_way: prompter