hydra:
  output_subdir: null
  run:
    # current dir when you read this file..
    dir: ./

defaults:
  - reward_lm: reward_lm
  - target_lm: vicuna-chat
  - prompter_lm: prompter_lm
  - _self_


reward_lm:
  debug: false
target_lm:
  debug: false
data_args:
  data_path: ./data/vicuna_process_100.json
  prompt_type: q_r_p
  train_ratio: 0.8

prompter_lm:
  model_name: /research/nfs_sun_397/liao.629/why_attack/ckpt/prompter_vicuna_ckpt_llama2-base_q_r_p
  # data .. ckpt original model ... prompt concatenation ...
  show_name: prompter_vicuna_ckpt_llama2-base_q_r_p
batch_size: 16
append_label_length: -1
s_p_t_dir: ./prompter_test_results
prompt_way: prompter