defaults:
  - reward_lm: reward_lm
  - target_lm: target_lm
  - _self_


reward_lm:
  debug: false
target_lm:
  debug: false

data: /home/liao.629/why_attack/data/reformatted_attack.jsonl
batch_size: 16
append_label_length: -1
s_p_t_dir: /home/liao.629/why_attack/s_p_t_evaluate
prompt_way: null



# reward_lm:
#   debug: true
#   model_name: gpt2
#   torch_dtype: bf16
# target_lm:
#   debug: true
#   model_name: gpt2
#   torch_dtype: bf16
# base_lm:
#   debug: true
#   model_name: stas/tiny-random-llama-2
#   torch_dtype: bf16
# trainer:
#   log_with: null
#   training_mode: sql-offpolicy
#   debug_off: true
#   num_epochs: 1
# data:
#   train: 1
#   test: 10
